name: Lint and Test

on:
  push:
    branches-ignore:
      - develop
      - main
      - gh-pages
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          # Test the most recent version Python 3 release
          # TODO: Enable again once pyserial had a new release which supports 3.14
          #- '3.x'
          # Temporarily set the highest supported Python version to 3.13, since pyserial currently doesn't work with 3.14
          # TODO: Remove once once pyserial had a new release which supports 3.14
          - '3.13'
          # Oldest version still receiving security updates and/or being used
          # in some Linux distributions
          - '3.10'
    name: Test python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install -r requirements-dev.txt

      - run: pytest --cov-fail-under=57
