name: Lint and Test

on:
  push:
    branches-ignore:
      - develop
      - main
      - gh-pages
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          # Test the most recent version Python 3 release
          - '3.x'
          # Test older version still in use by some distributions
          - '3.9'
    name: Test python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install -r requirements-dev.txt

      - run: pytest --cov-fail-under=57
